### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by UmerCodez** [ReneNyffenegger/VBA-calls-DLL#1]
Referring your C code at https://renenyffenegger.ch/notes/development/languages/VBA/Calling-DLLs/return-char-array

```
__declspec(dllexport) BSTR __stdcall bstr() {
    return SysAllocString(L"This bstr-string originates in C");
}
```

This piece of C code has memory leak as no call to `SysFreeString(BSTR)` has made after `SysAllocString()`

How can i assure that allocated `BSTR` returned in vba is properly released

**Comment by ReneNyffenegger** [comment]
My (unverified) understanding is that ownership of string that was allocated with `SysFreeString` is passed to the VBA runtime after assigning it to the VBA string and that this memory is freed by VBA's garbage collector when the string goes out of scope.

If my understanding is wrong, then indeed the string needs to be freed explicitely. But before I am going down that route, I need to verify my understanding.

**Comment by UmerCodez** [comment]
> My (unverified) understanding is that ownership of string that was allocated with `SysFreeString` is passed to the VBA runtime after assigning it to the VBA string and that this memory is freed by VBA's garbage collector when the string goes out of scope.
> 
> If my understanding is wrong, then indeed the string needs to be freed explicitely. But before I am going down that route, I need to verify my understanding.

I was thinking exactly the same thing that memory allocated with `SysAllocString(BSTR)` might be freed by VBA's garbage collector but i didn't find any authentic source to verify this except one answer on stackoverflow.com [(In VB6, do I need to call SysFreeString on strings allocated with SysAllocString?)](https://stackoverflow.com/questions/14280569/in-vb6-do-i-need-to-call-sysfreestring-on-strings-allocated-with-sysallocstring)

From above **stackoverflow.com** link i found another link (http://vb.mvps.org/tips/vb5dll/) which was a document published by **Microsoft** which shows some  examples of allocating `BSTR`  with `SysAllocStringByteLen` and returning them to VBA while not calling `SysFreeString` at VBA side

**Comment by ReneNyffenegger** [comment]
imho, these two links support my original assumption. Please let me know if I miss something.

**Comment by UmerCodez** [comment]
> imho, these two links support my original assumption. Please let me know if I miss something.

After reading contents of the two links it seems that your assumption is correct. 

You can now mark this issue as _**closed**_  

_(These readings might be helpful for someone who is looking for the same answer)_
